gll_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='about'),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('post/<str:post_id>', views.post, name='post'),
    path('create-post/', views.create_post, name='create_post'),
    path('update-post/<str:post_id>', views.update_post, name='update_post'),
    path('delete-post/<str:post_id>', views.delete_post, name='delete_post')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name="logout"),
    path('register', views.register_user, name="register"),
    path('edit-profile', views.edit_profile, name="profile-edit"),
]

templates/about.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url({% static 'images/anton-guitar.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">In a few words.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>In <strong>2019</strong> I have graduated from the <em>Financial University under
                    the Government
                    of the Russian Federation (Barnaul Branch)</em>.
                    After graduating, I was invited to work in a new startup project for the development of an
                    educational cryptocurrency online exchange. In time, I realized, that this work will not give me a
                    good future. Due to the pandemic,
                    the project was closed. After this I decided to search for what I really want to do in my life.
                    I wanted to do something interesting, something that can be really beneficial for people, not only
                    for myself,
                    and at the end of year 2020, I have made a very important decision to learn programming.
                    Before that time I knew nothing about programming. 
                </p>
                <p>On <strong> December 2021</strong> I've
                    got my first programmer job in the company <em>Sovcombank Technologies</em>, as a Python developer (Specialist).
                    <p><strong>My current job mostly includes:</strong></p>
                    <ul>
                      <li>Getting data from by API or from local files, parsing it and saving to database (SQL Oracle, sqlalchemy)</li>
                      <li>Automation processing of tasks in <a href="https://pyrus.com/en">"Pyrus"</a>, like: creating tasks, 
                      updating tasks, saving data from tasks to DB, writing comments and else.</li>
                      <li>Making notification bots, services for Telegram groups, email notifications.</li>
                      <li>Made various important bots, that are working with Active Directory, creating, 
                      updating and deleting Users, by getting info from tasks (by using LDAP library).</li>
                      <li>Made small service for storing cash in Redis (Using FastAPI, SQLAlchemy).</li>
                    </ul>
                    <p><strong>In free time at home learning, making myself familiar with:</strong></p>
                    <ul>
                      <li>JavaScript, Node.js React (took a course at Udemy to be able to understand core of web development).</li>
                      <li>At first year of learning programming, (by learning Python) made a website on Flask with help of the course from Udemy.</li>
                      <li>Django (Learning it now, by CS50, various courses and docs)</li>
                      <li>Helping my friend who is studying at University, to learn programming (C++, C#, Java, 
                        Python. Even if I never worked with Java, for example, it is much easier for me to understand basics, 
                        so I can explain it to my friend. 
                        While looking at his tasks, I'm also learning basics of these languages by myself and getting a good practice.</li>
                      <li>Slowly learning Japanese (by Anki, YouTube, a with help of my wonderfull Japanese friend).</li>
                    </ul>
                    <br>
                  </p>
                  <h1>My dream is what I live for.</h1>
                  <p>
                    I've started my programming path to be able to find a job in Japan later. To be a valuable employee there.
                    To make something good for Japan and for the World, if it would be possible. That's wonderfull thing, that
                    without any doubts, my decision to become a programmer was the best decision in my life.
                  </p>
                  <p>
                    And I'm still working on my dream and I will never stop.
                  </p>
                </br>
                <div>
                    <h3>Courses and qualifications:</h3>
                    <p>07.06.2021 - 07.10.2021
                        <a href="https://www.udemy.com/certificate/UC-542e3c6e-29bb-4bb2-a91c-c975fd9e6132/">Udemy (100
                            Days of Code - The Complete Python Pro Bootcamp for 2021)</a></p>
                    <p>2021年6月9日(水) <a href="https://www.careercross.com/en/">CareerCross Internship Program for English
                        Speakers in Japan</a></p>
                </div>
            </div>
        </div>
    </div>

    <br>

</main>

  <hr>

{% endblock %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'amicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'styles/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'about' %}">
                    <img src="{% static 'images/profiles/navbar-icon.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
                    Malyshev Anton</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'posts:posts' %}">All posts</a></li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link px-lg-3 py-3 py-lg-4 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              {{ request.user }}
                              <img src="{{ request.user.profile.profile_image.url }}" alt="" width="30" height="24" class="d-inline-block align-text-top">
                            </a>
                            <ul class="nav-item dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="{% url 'users:profile-edit' %}">Account Settings</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a></li>
                            </ul>
                          </li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:login' %}">Log In</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:register' %}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
    
        {% endblock content %}
        
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://github.com/Darkgll/python_learning_projects">
                                            <span class="fa-stack fa-lg">
                                                <i class="fas fa-circle fa-stack-2x"></i>
                                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                            </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.linkedin.com/in/anton-malyshev-0910b3215/">
                                            <span class="fa-stack fa-lg">
                                                <i class="fas fa-circle fa-stack-2x"></i>
                                                <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                                            </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.youtube.com/channel/UCtdz3QsgSPvN4uKmOHbE27A">
                                            <span class="fa-stack fa-lg">
                                                <i class="fas fa-circle fa-stack-2x"></i>
                                                <i class="fab fa-youtube fa-stack-1x fa-inverse"></i>
                                            </span>
                                </a>
                            </li>
                        </ul>
                        <p class="small text-center text-muted fst-italic">sanamyi7@gmail.com</p>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Malyshev Anton 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>