gll_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='about'),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('post/<str:post_id>', views.post, name='post'),
    path('create-post/', views.create_post, name='create_post'),
    path('update-post/<str:post_id>', views.update_post, name='update_post'),
    path('delete-post/<str:post_id>', views.delete_post, name='delete_post')
]

posts/models.py
from django.db import models
from django.core.validators import MaxLengthValidator
from users.models import Profile
import uuid


class Post(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    title = models.CharField(max_length=100, validators=[MaxLengthValidator(100)])
    author = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    subtitle = models.CharField(max_length=100, validators=[MaxLengthValidator(100)])
    futured_image = models.ImageField(null=True, blank=True, default="eyes-block-2.png")
    body = models.TextField(max_length=1000, validators=[MaxLengthValidator(1000)])
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Title: "{self.title}", subtitle: "{self.subtitle}", author username: "{self.author.username}"'


class Comment(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'Author username: "{self.author.username}", body: "{self.body}"'


# class Comment(models.Model):
#     author = models.ForeignKey(User, on_delete=models.CASCADE)
#     body = models.TextField(max_length=1000, validators=[MaxLengthValidator(1000)])

#     def __str__(self) -> str:
#         return f'Author: "{self.author}", body: "{self.body}"'

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'subtitle', 'futured_image',
                  'body']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Post
from .forms import PostForm, CommentForm


# Create your views here.
def posts(request):
    return render(request, 'posts/posts.html', {
        "posts": Post.objects.all()
    })


def post(request, post_id):
    try:
        post = Post.objects.get(id=post_id)
        form = CommentForm
        current_user = request.user.profile
    except Post.DoesNotExist:
        raise Http404("Post not found.")

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = current_user
            comment.save()
            return redirect('posts:post', post_id=post_id)
    
    return render(request, "posts/post.html", {
        "post": post,
        "form": form
    })


@login_required(login_url='login')
def update_post(request, post_id):
    post = Post.objects.get(id=post_id)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:posts')
    
    return render(request, 'posts/post_form.html', {
        'form': form,
        'edit': True
    })


@login_required(login_url='login')
def create_post(request):
    form = PostForm()
    current_user = request.user.profile

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            
            post = form.save(commit=False)
            post.author = current_user
            post.save()
            
            return redirect('posts:posts')
    return render(request, 'posts/post_form.html', {
        'form': form
    })


def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('posts:posts')
    return render(request, 'posts/posts.html')

posts/templates/posts/post.html
{% extends 'main.html' %}
{% block content %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({{ post.futured_image.url }})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{ post.title }}</h1>
                            <h2 class="subheading">{{ post.subtitle }}</h2>
                            <span class="meta">
                                Posted by
                                {{ post.author }}
                                on {{ post.created }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>
                            {{ post.body|linebreaks }}
                        </p>
                    </div>
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <a class="btn btn-primary text-uppercase" href="{% url 'posts:update_post' post.id %}">Edit Post</a>
                    </div>
                </div>
            </div>
        </article>
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% for comment in post.comment_set.all %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <p class="mb-0 border border-primary">{{ comment.author|title }}</p>
                        <div class="p-2 bg-light border border-primary">
                            <p>
                                {{ comment.body|linebreaks }}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="my-5">
                        <form id="postForm" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            </div>
                            <p>Share your thougts...</p>
                            <div class="form-floating">
                                {{ form.body.errors }}
                                <textarea class="form-control border" type="text" required="required" placeholder="Your post..." name="body" rows="2"></textarea>
                            </div>
                            <br />
                            <!-- Submit Button-->
                            <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send comment...</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<!-- Page Header-->
{% if edit %}
<header class="masthead" style="background-image: url({{ form.futured_image.value.url }})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{ form.title.value }}</h1>
                    <h2 class="subheading">{{ form.subtitle.value }}</h2>
                    <span class="meta">
                        Posted by
                        {{ form.author.value }}
                        on {{ form.created.value }}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% else %}
<header class="masthead" style="background-image: url({% static 'images/marek-okon-fpbWloKiYVY-unsplash.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Create your own post!</h1>
                    </br>
                    <span class="subheading">Share your thougts, dreams and feelings!</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endif %}
<!-- Main Content-->

<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="my-5">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert {{ message.extra_tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    
                    <form id="postForm" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        </div>
                        <div class="form-floating">
                            {{ form.title.errors }}
                            <input class="form-control" type="text" autofocus="autofocus" required="required" id="{{ form.title.label }}" value="{{ form.title.value }}" placeholder="{{ form.title.value }}" name='title'/>
                            <label for="{{ form.title.label }}">{{ form.title.label }}</label>
                        </div>
                        <div class="form-floating">
                            {{ form.subtitle.errors }}
                            <input class="form-control" type="text" required="required" id="{{ form.subtitle.label }}" value="{{ form.subtitle.value }}" placeholder="{{ form.subtitle.label }}" name='subtitle'/>
                            <label for="{{ form.subtitle.label }}">{{ form.subtitle.label }}</label>
                        </div>
                        <div class="mb-3">
                            {{ form.body.errors }}
                            <textarea class="form-control" type="text" required="required" placeholder="Your post..." name="body" rows="10">{{ form.body.value }}</textarea>
                        </div>
                        <br />
                        <div class="mb-3">
                            {{ form.futured_image.errors }}
                            <label for="{{ form.futured_image.label }}" class="form-label">Upload image for a post</label>
                            <input class="form-control form-control-lg" type="file" id="{{ form.futured_image.label }}" name="futured_image">
                        </div>
                        <br />
                        <!-- Submit Button-->
                        <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Submit Post...</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

posts/templates/posts/posts.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% static 'images/marek-okon-fpbWloKiYVY-unsplash.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% if messages %}
            {% for message in messages %}
            <div class="alert {{ message.extra_tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            {% for post in posts %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'posts:post' post.id %}">
                    <h2 class="post-title">{{ post.title }}</h2>
                    <h3 class="post-subtitle">{{ post.subtitle }}</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="{% url 'posts:post' post.id %}">{{ post.author|title }}</a>
                    on {{ post.created }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7">
            <a class="btn btn-primary text-uppercase" href="{% url 'posts:create_post' %}">Make new post...</a>
        </div>
    </div>
    <br />
</div>
{% endblock %}